// packages/react/src/components/radio-group/radio-group-context.ts
import { createContext, useContext } from 'react'

// =============================================================================
// TODO: 定義 RadioGroup 的 Context
// =============================================================================
//
// 💡 提示：
// 1. 定義 Context 的形狀（RadioGroupContextValue interface）
// 2. 用 createContext 建立 Context（預設值設為 null）
// 3. 建立 useRadioGroupContext hook，加上防護性錯誤處理
//
// Context 需要包含的欄位：
//   - value: string  →  目前選中的值
//   - setValue: (value: string) => void  →  更新選中值
//   - name: string  →  表單欄位名稱（供 input[name] 使用）
//
// 📖 參考：
// - createContext: https://react.dev/reference/react/createContext
// - Ark UI 自訂 createContext 範例：https://github.com/chakra-ui/ark/blob/main/packages/react/src/utils/create-context.ts
// =============================================================================

// TODO: 定義 RadioGroupContextValue interface
// export interface RadioGroupContextValue {
//   value: string
//   setValue: (value: string) => void
//   name: string
// }

// TODO: 建立 Context
// export const RadioGroupContext = createContext<RadioGroupContextValue | null>(null)

// TODO: 建立 useRadioGroupContext hook
// export function useRadioGroupContext(): RadioGroupContextValue {
//   const context = useContext(RadioGroupContext)
//   if (!context) {
//     throw new Error('useRadioGroupContext must be used within <RadioGroup.Root>')
//   }
//   return context
// }

// packages/solid/src/components/radio-group/radio-group-context.ts
import { createContext, useContext } from 'solid-js'

// =============================================================================
// TODO: 定義 RadioGroup 的 Solid Context
// =============================================================================
//
// 💡 提示（Solid 與 React 的差異）：
// - Solid 的 createContext 需要傳入預設值，不能是 null（或加型別斷言）
// - 通常的做法是不傳預設值，在 use hook 中檢查是否為 undefined
// - Solid 的狀態用 createSignal、createMemo 等 primitive
//
// Context 需要包含：
//   - value: string  →  目前選中的值
//   - setValue: (value: string) => void  →  更新選中值
//   - name: string  →  表單欄位名稱（供 input[name] 使用）
//
// 📖 參考：
// - Solid createContext: https://www.solidjs.com/docs/latest#createcontext
// - Solid Accessor pattern: https://www.solidjs.com/tutorial/stores_createstore
// =============================================================================

// TODO: 定義型別
// export interface RadioGroupContextValue {
//   value: string
//   setValue: (value: string) => void
//   name: string
// }

// TODO: 建立 Context
// const RadioGroupContext = createContext<RadioGroupContextValue>()

// TODO: 建立 use hook
// export function useRadioGroupContext(): RadioGroupContextValue {
//   const context = useContext(RadioGroupContext)
//   if (!context) {
//     throw new Error('useRadioGroupContext must be used within <RadioGroup.Root>')
//   }
//   return context
// }
