// packages/solid/src/components/switch/switch-root.tsx
import type { ParentProps } from 'solid-js'
import { createSignal } from 'solid-js'

// =============================================================================
// TODO: 實作 SwitchRoot（Solid 版）
// =============================================================================
//
// 💡 Solid 與 React 的主要差異：
// - 狀態管理：createSignal 代替 useState
//   const [value, setValue] = createSignal(defaultValue)
// - 沒有 forwardRef：Solid 5 使用 ref prop 直接傳遞
// - Context：用 <SwitchContext.Provider value={...}> 包住
//
// 架構重點：
// - 和 Checkbox 非常相似，但 HiddenInput 用 role="switch" 而非預設的 checkbox role
// - Switch 只有 on/off 兩種狀態（不像 Checkbox 有 indeterminate）
//
// 📖 參考：
// - Solid Signals: https://www.solidjs.com/docs/latest#createsignal
// - Solid Context: https://www.solidjs.com/docs/latest#createcontext
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/switch/
// - Zag.js 參考: https://zagjs.com/components/react/switch
// =============================================================================

export interface SwitchRootProps extends ParentProps {
  // TODO: 定義 props
}

export function SwitchRoot(props: SwitchRootProps) {
  // TODO: createSignal 管理狀態

  // TODO: 建立 context value

  // TODO: 渲染 Provider + div
  return null // ← 替換這行
}

// packages/react/src/components/switch/switch-root.tsx
import { forwardRef } from 'react'
import type { ComponentPropsWithoutRef } from 'react'

// =============================================================================
// TODO: 實作 SwitchRoot
// =============================================================================
//
// 這是 Switch 的根容器，職責：
//   1. 接受 props（受控 value + 非受控 defaultValue）
//   2. 用 useState 管理內部狀態
//   3. 透過 Context Provider 把狀態傳遞給子元件
//   4. 渲染 <div> 並加上適當的 data-state 屬性
//
// 💡 架構重點：
//   - 和 Checkbox 非常相似，但 HiddenInput 用 role="switch" 而非預設的 checkbox role
//   - Switch 只有 on/off 兩種狀態（不像 Checkbox 有 indeterminate）
//   - Control + Thumb 是視覺層，用 CSS transform 做滑動動畫
//
// 📖 參考：
// - forwardRef: https://react.dev/reference/react/forwardRef
// - 受控 vs 非受控: https://react.dev/learn/sharing-state-between-components
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/switch/
// - Zag.js 狀態機參考: https://zagjs.com/components/react/switch
// =============================================================================

export interface SwitchRootProps extends ComponentPropsWithoutRef<'div'> {
  // TODO: 定義 props
  // defaultValue?: ...   ← 非受控模式的初始值
  // value?: ...          ← 受控模式的值
  // onValueChange?: ...  ← 狀態改變的回調
  // disabled?: boolean   ← 是否禁用
}

export const SwitchRoot = forwardRef<HTMLDivElement, SwitchRootProps>(
  (props, ref) => {
    // TODO: 解構 props
    // const { children, defaultValue, value, onValueChange, disabled, ...htmlProps } = props

    // TODO: 用 useState 管理內部狀態（非受控）
    // const [internalValue, setInternalValue] = useState(defaultValue ?? ...)

    // TODO: 建立 Context value 物件

    // TODO: 渲染 Context Provider + <div>
    return null // ← 替換這行
  },
)

SwitchRoot.displayName = 'SwitchRoot'
