// packages/solid/src/components/select/select-item-group-label.tsx
import type { ComponentProps } from 'solid-js'
import { splitProps } from 'solid-js'

// =============================================================================
// TODO: 實作 SelectItemGroupLabel（Solid 版）
// =============================================================================
//
// 功能說明：分組標籤
//
// 💡 Solid 技巧：
// - 使用 splitProps 分離元件專屬 props 和原生 HTML props
//   const [local, others] = splitProps(props, ['特定prop1', '特定prop2'])
// - Solid 的屬性是 getter，直接存取 props.xxx 即可（反應式）
// - 用 <Dynamic> 元件可以動態選擇標籤（可選）
//
// 📖 參考：
// - splitProps: https://www.solidjs.com/docs/latest#splitprops
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
// - Ark UI SelectItemGroupLabel Solid 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/solid/src/components/select/select-item-group-label.tsx
// =============================================================================

export interface SelectItemGroupLabelProps extends ComponentProps<'div'> {
  // TODO: 額外 props
}

export function SelectItemGroupLabel(props: SelectItemGroupLabelProps) {
  // TODO: 從 Context 讀取狀態
  // const context = useSelectContext()

  // TODO: splitProps
  // const [local, others] = splitProps(props, [...])

  // TODO: 渲染
  return null // ← 替換這行
}

// packages/react/src/components/select/select-item-group-label.tsx
import { forwardRef } from 'react'
import type { ComponentPropsWithoutRef } from 'react'

// =============================================================================
// TODO: 實作 SelectItemGroupLabel
// =============================================================================
//
// 功能說明：分組標籤
//
// 💡 提示：
// Step 1 — 從 Context 讀取需要的狀態
//   使用 useSelectContext() 取得所需資料
//
// Step 2 — ARIA 無障礙屬性
//   參考 https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
//   決定此元素需要哪些 aria-* 和 role 屬性
//
// Step 3 — 事件處理
//   實作互動行為，並保留使用者傳入的 event handler
//   例：const handleClick = (e) => { props.onClick?.(e); doSomething() }
//
// Step 4 — data-* 屬性
//   加上 data-state、data-disabled 等屬性供 CSS 使用
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
// - Ark UI SelectItemGroupLabel 實作參考：
//   https://github.com/chakra-ui/ark/blob/main/packages/react/src/components/select/select-item-group-label.tsx
// =============================================================================

export interface SelectItemGroupLabelProps extends ComponentPropsWithoutRef<'div'> {
  // TODO: 是否需要額外的 props？
}

export const SelectItemGroupLabel = forwardRef<HTMLDivElement, SelectItemGroupLabelProps>(
  (props, ref) => {
    // TODO: 從 Context 讀取狀態
    // const { ... } = useSelectContext()

    // TODO: 實作邏輯

    // TODO: 渲染
    return null // ← 替換這行
  },
)

SelectItemGroupLabel.displayName = 'SelectItemGroupLabel'
