// packages/svelte/src/components/tooltip/TooltipTrigger.svelte
<script lang="ts">
  // ===========================================================================
  // TODO: 實作 TooltipTrigger（Svelte 5 版）
  // ===========================================================================
  //
  // 功能說明：觸發 Tooltip 顯示的元素
  //
  // 💡 提示：
  // Step 1 — 從 Context 讀取狀態
  //   import { getTooltipContext } from './tooltip-context.svelte.ts'
  //   const context = getTooltipContext()
  //
  // Step 2 — 計算 ARIA 屬性（使用 $derived）
  //   const isExpanded = $derived(context.value === props.value)
  //
  // Step 3 — 事件處理（Svelte 5 用 onclick 代替 on:click）
  //
  // 📖 參考：
  // - Svelte 5 $derived: https://svelte.dev/docs/svelte/$derived
  // - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/
  // - Ark UI TooltipTrigger Svelte 版本：
  //   https://github.com/chakra-ui/ark/blob/main/packages/svelte/src/lib/components/tooltip/TooltipTrigger.svelte
  // ===========================================================================

  // TODO: import context
  // const context = getTooltipContext()

  // TODO: $derived 計算屬性
</script>

<!-- TODO: 渲染 <button> 並加上 ARIA 屬性 -->
<button>
  {@render children?.()}
</button>

// packages/vue/src/components/tooltip/TooltipTrigger.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 TooltipTrigger Vue 元件
// =============================================================================
//
// 功能說明：觸發 Tooltip 顯示的元素
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { useTooltipContext } from './tooltip-context'
//   const context = useTooltipContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/
// - Ark UI TooltipTrigger Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/tooltip/TooltipTrigger.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = useTooltipContext()
</script>

<template>
  <!-- TODO: 渲染 <button> 並加上 ARIA 屬性 -->
  <button v-bind="$attrs">
    <slot />
  </button>
</template>
