// packages/svelte/src/components/collapsible/CollapsibleContent.svelte
<script lang="ts">
  // ===========================================================================
  // TODO: 實作 CollapsibleContent（Svelte 5 版）
  // ===========================================================================
  //
  // 功能說明：可收合的內容區域
  //
  // 💡 提示：
  // Step 1 — 從 Context 讀取狀態
  //   import { getCollapsibleContext } from './collapsible-context.svelte.ts'
  //   const context = getCollapsibleContext()
  //
  // Step 2 — 計算 ARIA 屬性（使用 $derived）
  //   const isExpanded = $derived(context.value === props.value)
  //
  // Step 3 — 事件處理（Svelte 5 用 onclick 代替 on:click）
  //
  // 📖 參考：
  // - Svelte 5 $derived: https://svelte.dev/docs/svelte/$derived
  // - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/
  // - Ark UI CollapsibleContent Svelte 版本：
  //   https://github.com/chakra-ui/ark/blob/main/packages/svelte/src/lib/components/collapsible/CollapsibleContent.svelte
  // ===========================================================================

  // TODO: import context
  // const context = getCollapsibleContext()

  // TODO: $derived 計算屬性
</script>

<!-- TODO: 渲染 <div> 並加上 ARIA 屬性 -->
<div>
  {@render children?.()}
</div>

// packages/vue/src/components/collapsible/CollapsibleContent.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 CollapsibleContent Vue 元件
// =============================================================================
//
// 功能說明：可收合的內容區域
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { useCollapsibleContext } from './collapsible-context'
//   const context = useCollapsibleContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/
// - Ark UI CollapsibleContent Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/collapsible/CollapsibleContent.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = useCollapsibleContext()
</script>

<template>
  <!-- TODO: 渲染 <div> 並加上 ARIA 屬性 -->
  <div v-bind="$attrs">
    <slot />
  </div>
</template>
