// packages/react/src/components/collapsible/collapsible-trigger.tsx
import { forwardRef } from 'react'
import type { ComponentPropsWithoutRef } from 'react'

// =============================================================================
// TODO: 實作 CollapsibleTrigger
// =============================================================================
//
// 這是觸發展開/收合的按鈕，職責：
//   1. 從 Context 讀取 toggle 函式和 open 狀態
//   2. 點擊時呼叫 toggle
//   3. 加上正確的 ARIA 屬性
//
// 💡 提示：
//
// Step 1 — 從 Context 讀取狀態
//   使用你在 collapsible-context.ts 定義的 useCollapsibleContext
//
// Step 2 — ARIA 無障礙屬性
//   <button> 需要以下屬性：
//   - aria-expanded={open}        → 告訴螢幕閱讀器目前是展開還是收合
//   - aria-controls={contentId}   → 指向被控制的內容區域的 ID
//   - data-state="open" | "closed" → 讓 CSS 可以依狀態設定樣式
//   - disabled={disabled}         → 是否禁用
//
// Step 3 — 事件處理
//   - onClick → 呼叫 toggle（如果沒有 disabled）
//   💡 記得也要保留使用者傳入的 onClick！
//      const handleClick = (e) => {
//        props.onClick?.(e)  // 先呼叫使用者的
//        toggle()            // 再執行 toggle
//      }
//
// 📖 參考：
// - WAI-ARIA Disclosure Pattern:
//   https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/
// =============================================================================

export interface CollapsibleTriggerProps extends ComponentPropsWithoutRef<'button'> {
  // TODO: 需要額外的 props 嗎？
}

export const CollapsibleTrigger = forwardRef<HTMLButtonElement, CollapsibleTriggerProps>(
  (props, ref) => {
    // TODO: 從 Context 讀取狀態

    // TODO: 處理點擊事件

    // TODO: 渲染 <button> 並加上 ARIA 屬性
    return null // ← 替換這行
  },
)

CollapsibleTrigger.displayName = 'CollapsibleTrigger'

// packages/vue/src/components/collapsible/CollapsibleTrigger.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 CollapsibleTrigger Vue 元件
// =============================================================================
//
// 功能說明：觸發展開/收合的按鈕
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { useCollapsibleContext } from './collapsible-context'
//   const context = useCollapsibleContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/
// - Ark UI CollapsibleTrigger Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/collapsible/CollapsibleTrigger.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = useCollapsibleContext()
</script>

<template>
  <!-- TODO: 渲染 <button> 並加上 ARIA 屬性 -->
  <button v-bind="$attrs">
    <slot />
  </button>
</template>
