// packages/vue/src/components/checkbox/CheckboxIndicator.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 CheckboxIndicator Vue 元件
// =============================================================================
//
// 功能說明：打勾標記（checked 時顯示）
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { useCheckboxContext } from './checkbox-context'
//   const context = useCheckboxContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/
// - Ark UI CheckboxIndicator Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/checkbox/CheckboxIndicator.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = useCheckboxContext()
</script>

<template>
  <!-- TODO: 渲染 <span> 並加上 ARIA 屬性 -->
  <span v-bind="$attrs">
    <slot />
  </span>
</template>

// packages/solid/src/components/checkbox/checkbox-indicator.tsx
import type { ComponentProps } from 'solid-js'
import { splitProps } from 'solid-js'

// =============================================================================
// TODO: 實作 CheckboxIndicator（Solid 版）
// =============================================================================
//
// 功能說明：打勾標記（checked 時顯示）
//
// 💡 Solid 技巧：
// - 使用 splitProps 分離元件專屬 props 和原生 HTML props
//   const [local, others] = splitProps(props, ['特定prop1', '特定prop2'])
// - Solid 的屬性是 getter，直接存取 props.xxx 即可（反應式）
// - 用 <Dynamic> 元件可以動態選擇標籤（可選）
//
// 📖 參考：
// - splitProps: https://www.solidjs.com/docs/latest#splitprops
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/
// - Ark UI CheckboxIndicator Solid 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/solid/src/components/checkbox/checkbox-indicator.tsx
// =============================================================================

export interface CheckboxIndicatorProps extends ComponentProps<'span'> {
  // TODO: 額外 props
}

export function CheckboxIndicator(props: CheckboxIndicatorProps) {
  // TODO: 從 Context 讀取狀態
  // const context = useCheckboxContext()

  // TODO: splitProps
  // const [local, others] = splitProps(props, [...])

  // TODO: 渲染
  return null // ← 替換這行
}
