// packages/vue/src/components/checkbox/CheckboxHiddenInput.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 CheckboxHiddenInput Vue 元件
// =============================================================================
//
// 功能說明：真實的 input[type="checkbox"]（視覺隱藏，供表單使用）
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { useCheckboxContext } from './checkbox-context'
//   const context = useCheckboxContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/
// - Ark UI CheckboxHiddenInput Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/checkbox/CheckboxHiddenInput.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = useCheckboxContext()
</script>

<template>
  <!-- TODO: 渲染 <input> 並加上 ARIA 屬性 -->
  <input v-bind="$attrs">
    <slot />
  </input>
</template>

// packages/react/src/components/checkbox/checkbox-hidden-input.tsx
import { forwardRef } from 'react'
import type { ComponentPropsWithoutRef } from 'react'

// =============================================================================
// TODO: 實作 CheckboxHiddenInput
// =============================================================================
//
// 功能說明：真實的 input[type="checkbox"]（視覺隱藏，供表單使用）
//
// 💡 提示：
// Step 1 — 從 Context 讀取需要的狀態
//   使用 useCheckboxContext() 取得所需資料
//
// Step 2 — ARIA 無障礙屬性
//   參考 https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/
//   決定此元素需要哪些 aria-* 和 role 屬性
//
// Step 3 — 事件處理
//   實作互動行為，並保留使用者傳入的 event handler
//   例：const handleClick = (e) => { props.onClick?.(e); doSomething() }
//
// Step 4 — data-* 屬性
//   加上 data-state、data-disabled 等屬性供 CSS 使用
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/
// - Ark UI CheckboxHiddenInput 實作參考：
//   https://github.com/chakra-ui/ark/blob/main/packages/react/src/components/checkbox/checkbox-hidden-input.tsx
// =============================================================================

export interface CheckboxHiddenInputProps extends ComponentPropsWithoutRef<'input'> {
  // TODO: 是否需要額外的 props？
}

export const CheckboxHiddenInput = forwardRef<HTMLInputElement, CheckboxHiddenInputProps>(
  (props, ref) => {
    // TODO: 從 Context 讀取狀態
    // const { ... } = useCheckboxContext()

    // TODO: 實作邏輯

    // TODO: 渲染
    return null // ← 替換這行
  },
)

CheckboxHiddenInput.displayName = 'CheckboxHiddenInput'
