// packages/solid/src/components/checkbox/checkbox-context.ts
import { createContext, useContext } from 'solid-js'

// =============================================================================
// TODO: 定義 Checkbox 的 Solid Context
// =============================================================================
//
// 💡 提示（Solid 與 React 的差異）：
// - Solid 的 createContext 需要傳入預設值，不能是 null（或加型別斷言）
// - 通常的做法是不傳預設值，在 use hook 中檢查是否為 undefined
// - Solid 的狀態用 createSignal、createMemo 等 primitive
//
// Context 需要包含：
//   - checked: boolean | "indeterminate"  →  勾選狀態（支援不確定狀態）
//   - setChecked: (checked: boolean | "indeterminate") => void  →  更新狀態
//   - disabled: boolean  →  是否禁用
//   - inputId: string  →  HiddenInput 的 id
//
// 📖 參考：
// - Solid createContext: https://www.solidjs.com/docs/latest#createcontext
// - Solid Accessor pattern: https://www.solidjs.com/tutorial/stores_createstore
// =============================================================================

// TODO: 定義型別
// export interface CheckboxContextValue {
//   checked: boolean | "indeterminate"
//   setChecked: (checked: boolean | "indeterminate") => void
//   disabled: boolean
//   inputId: string
// }

// TODO: 建立 Context
// const CheckboxContext = createContext<CheckboxContextValue>()

// TODO: 建立 use hook
// export function useCheckboxContext(): CheckboxContextValue {
//   const context = useContext(CheckboxContext)
//   if (!context) {
//     throw new Error('useCheckboxContext must be used within <Checkbox.Root>')
//   }
//   return context
// }

// packages/react/src/components/checkbox/checkbox-context.ts
import { createContext, useContext } from 'react'

// =============================================================================
// TODO: 定義 Checkbox 的 Context
// =============================================================================
//
// 💡 提示：
// 1. 定義 Context 的形狀（CheckboxContextValue interface）
// 2. 用 createContext 建立 Context（預設值設為 null）
// 3. 建立 useCheckboxContext hook，加上防護性錯誤處理
//
// Context 需要包含的欄位：
//   - checked: boolean | "indeterminate"  →  勾選狀態（支援不確定狀態）
//   - setChecked: (checked: boolean | "indeterminate") => void  →  更新狀態
//   - disabled: boolean  →  是否禁用
//   - inputId: string  →  HiddenInput 的 id
//
// 📖 參考：
// - createContext: https://react.dev/reference/react/createContext
// - Ark UI 自訂 createContext 範例：https://github.com/chakra-ui/ark/blob/main/packages/react/src/utils/create-context.ts
// =============================================================================

// TODO: 定義 CheckboxContextValue interface
// export interface CheckboxContextValue {
//   checked: boolean | "indeterminate"
//   setChecked: (checked: boolean | "indeterminate") => void
//   disabled: boolean
//   inputId: string
// }

// TODO: 建立 Context
// export const CheckboxContext = createContext<CheckboxContextValue | null>(null)

// TODO: 建立 useCheckboxContext hook
// export function useCheckboxContext(): CheckboxContextValue {
//   const context = useContext(CheckboxContext)
//   if (!context) {
//     throw new Error('useCheckboxContext must be used within <Checkbox.Root>')
//   }
//   return context
// }
