// packages/svelte/src/components/select/SelectLabel.svelte
<script lang="ts">
  // ===========================================================================
  // TODO: 實作 SelectLabel（Svelte 5 版）
  // ===========================================================================
  //
  // 功能說明：選單標籤
  //
  // 💡 提示：
  // Step 1 — 從 Context 讀取狀態
  //   import { getSelectContext } from './select-context.svelte.ts'
  //   const context = getSelectContext()
  //
  // Step 2 — 計算 ARIA 屬性（使用 $derived）
  //   const isExpanded = $derived(context.value === props.value)
  //
  // Step 3 — 事件處理（Svelte 5 用 onclick 代替 on:click）
  //
  // 📖 參考：
  // - Svelte 5 $derived: https://svelte.dev/docs/svelte/$derived
  // - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
  // - Ark UI SelectLabel Svelte 版本：
  //   https://github.com/chakra-ui/ark/blob/main/packages/svelte/src/lib/components/select/SelectLabel.svelte
  // ===========================================================================

  // TODO: import context
  // const context = getSelectContext()

  // TODO: $derived 計算屬性
</script>

<!-- TODO: 渲染 <label> 並加上 ARIA 屬性 -->
<label>
  {@render children?.()}
</label>

// packages/vue/src/components/select/SelectLabel.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 SelectLabel Vue 元件
// =============================================================================
//
// 功能說明：選單標籤
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { useSelectContext } from './select-context'
//   const context = useSelectContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
// - Ark UI SelectLabel Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/select/SelectLabel.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = useSelectContext()
</script>

<template>
  <!-- TODO: 渲染 <label> 並加上 ARIA 屬性 -->
  <label v-bind="$attrs">
    <slot />
  </label>
</template>
