// packages/vue/src/components/avatar/AvatarImage.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 AvatarImage Vue 元件
// =============================================================================
//
// 功能說明：頭像圖片（載入失敗時隱藏）
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { useAvatarContext } from './avatar-context'
//   const context = useAvatarContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/
// - Ark UI AvatarImage Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/avatar/AvatarImage.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = useAvatarContext()
</script>

<template>
  <!-- TODO: 渲染 <img> 並加上 ARIA 屬性 -->
  <img v-bind="$attrs">
    <slot />
  </img>
</template>

// packages/svelte/src/components/avatar/AvatarImage.svelte
<script lang="ts">
  // ===========================================================================
  // TODO: 實作 AvatarImage（Svelte 5 版）
  // ===========================================================================
  //
  // 功能說明：頭像圖片（載入失敗時隱藏）
  //
  // 💡 提示：
  // Step 1 — 從 Context 讀取狀態
  //   import { getAvatarContext } from './avatar-context.svelte.ts'
  //   const context = getAvatarContext()
  //
  // Step 2 — 計算 ARIA 屬性（使用 $derived）
  //   const isExpanded = $derived(context.value === props.value)
  //
  // Step 3 — 事件處理（Svelte 5 用 onclick 代替 on:click）
  //
  // 📖 參考：
  // - Svelte 5 $derived: https://svelte.dev/docs/svelte/$derived
  // - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/
  // - Ark UI AvatarImage Svelte 版本：
  //   https://github.com/chakra-ui/ark/blob/main/packages/svelte/src/lib/components/avatar/AvatarImage.svelte
  // ===========================================================================

  // TODO: import context
  // const context = getAvatarContext()

  // TODO: $derived 計算屬性
</script>

<!-- TODO: 渲染 <img> 並加上 ARIA 屬性 -->
<img>
  {@render children?.()}
</img>
