// packages/solid/src/components/select/select-value-text.tsx
import type { ComponentProps } from 'solid-js'
import { splitProps } from 'solid-js'

// =============================================================================
// TODO: 實作 SelectValueText（Solid 版）
// =============================================================================
//
// 功能說明：顯示目前選中的值文字
//
// 💡 Solid 技巧：
// - 使用 splitProps 分離元件專屬 props 和原生 HTML props
//   const [local, others] = splitProps(props, ['特定prop1', '特定prop2'])
// - Solid 的屬性是 getter，直接存取 props.xxx 即可（反應式）
// - 用 <Dynamic> 元件可以動態選擇標籤（可選）
//
// 📖 參考：
// - splitProps: https://www.solidjs.com/docs/latest#splitprops
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
// - Ark UI SelectValueText Solid 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/solid/src/components/select/select-value-text.tsx
// =============================================================================

export interface SelectValueTextProps extends ComponentProps<'span'> {
  // TODO: 額外 props
}

export function SelectValueText(props: SelectValueTextProps) {
  // TODO: 從 Context 讀取狀態
  // const context = useSelectContext()

  // TODO: splitProps
  // const [local, others] = splitProps(props, [...])

  // TODO: 渲染
  return null // ← 替換這行
}

// packages/svelte/src/components/select/SelectValueText.svelte
<script lang="ts">
  // ===========================================================================
  // TODO: 實作 SelectValueText（Svelte 5 版）
  // ===========================================================================
  //
  // 功能說明：顯示目前選中的值文字
  //
  // 💡 提示：
  // Step 1 — 從 Context 讀取狀態
  //   import { getSelectContext } from './select-context.svelte.ts'
  //   const context = getSelectContext()
  //
  // Step 2 — 計算 ARIA 屬性（使用 $derived）
  //   const isExpanded = $derived(context.value === props.value)
  //
  // Step 3 — 事件處理（Svelte 5 用 onclick 代替 on:click）
  //
  // 📖 參考：
  // - Svelte 5 $derived: https://svelte.dev/docs/svelte/$derived
  // - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
  // - Ark UI SelectValueText Svelte 版本：
  //   https://github.com/chakra-ui/ark/blob/main/packages/svelte/src/lib/components/select/SelectValueText.svelte
  // ===========================================================================

  // TODO: import context
  // const context = getSelectContext()

  // TODO: $derived 計算屬性
</script>

<!-- TODO: 渲染 <span> 並加上 ARIA 屬性 -->
<span>
  {@render children?.()}
</span>
