// packages/solid/src/components/checkbox/checkbox-root.tsx
import type { ParentProps } from 'solid-js'
import { createSignal } from 'solid-js'

// =============================================================================
// TODO: 實作 CheckboxRoot（Solid 版）
// =============================================================================
//
// 💡 Solid 與 React 的主要差異：
// - 狀態管理：createSignal 代替 useState
//   const [value, setValue] = createSignal(defaultValue)
// - 沒有 forwardRef：Solid 5 使用 ref prop 直接傳遞
// - Context：用 <CheckboxContext.Provider value={...}> 包住
//
// 架構重點：
// - Control + Indicator 是視覺層，HiddenInput 是語義/表單層（兩者都需要）
// - 支援 indeterminate（不確定）狀態：data-state="indeterminate"
//
// 📖 參考：
// - Solid Signals: https://www.solidjs.com/docs/latest#createsignal
// - Solid Context: https://www.solidjs.com/docs/latest#createcontext
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/
// - Zag.js 參考: https://zagjs.com/components/react/checkbox
// =============================================================================

export interface CheckboxRootProps extends ParentProps {
  // TODO: 定義 props
}

export function CheckboxRoot(props: CheckboxRootProps) {
  // TODO: createSignal 管理狀態

  // TODO: 建立 context value

  // TODO: 渲染 Provider + div
  return null // ← 替換這行
}

// packages/svelte/src/components/checkbox/CheckboxRoot.svelte
<script lang="ts">
  // ===========================================================================
  // TODO: 實作 CheckboxRoot（Svelte 5 版）
  // ===========================================================================
  //
  // 💡 提示（Svelte 5 Runes）：
  // - 使用 $props() 取得 props（代替 export let）
  // - 使用 $state() 建立反應式狀態
  // - 使用 setContext / setCheckboxContext 把狀態分享給子元件
  //
  // 架構重點：
  // - Control + Indicator 是視覺層，HiddenInput 是語義/表單層（兩者都需要）
  // - 支援 indeterminate（不確定）狀態：data-state="indeterminate"
  //
  // 📖 參考：
  // - Svelte 5 $props: https://svelte.dev/docs/svelte/$props
  // - Svelte 5 $state: https://svelte.dev/docs/svelte/$state
  // - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/
  // - Zag.js 參考: https://zagjs.com/components/react/checkbox
  // ===========================================================================

  // TODO: 定義 Props（Svelte 5 方式）
  // interface Props {
  //   value?: ...
  //   defaultValue?: ...
  //   onValueChange?: (value: ...) => void
  //   children?: import('svelte').Snippet
  // }
  // const { ...props }: Props = $props()

  // TODO: 狀態管理（$state）
  // let internalValue = $state(props.defaultValue ?? ...)

  // TODO: setContext
  // setCheckboxContext({ ... })
</script>

<!-- TODO: 渲染根容器 -->
<!-- 提示：加上 data-state 屬性供 CSS 使用 -->
<div>
  {@render children?.()}
</div>
