// packages/vue/src/components/switch/SwitchHiddenInput.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 SwitchHiddenInput Vue 元件
// =============================================================================
//
// 功能說明：底層的 input[type="checkbox" role="switch"]
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { useSwitchContext } from './switch-context'
//   const context = useSwitchContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/switch/
// - Ark UI SwitchHiddenInput Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/switch/SwitchHiddenInput.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = useSwitchContext()
</script>

<template>
  <!-- TODO: 渲染 <input> 並加上 ARIA 屬性 -->
  <input v-bind="$attrs">
    <slot />
  </input>
</template>

// packages/svelte/src/components/switch/SwitchHiddenInput.svelte
<script lang="ts">
  // ===========================================================================
  // TODO: 實作 SwitchHiddenInput（Svelte 5 版）
  // ===========================================================================
  //
  // 功能說明：底層的 input[type="checkbox" role="switch"]
  //
  // 💡 提示：
  // Step 1 — 從 Context 讀取狀態
  //   import { getSwitchContext } from './switch-context.svelte.ts'
  //   const context = getSwitchContext()
  //
  // Step 2 — 計算 ARIA 屬性（使用 $derived）
  //   const isExpanded = $derived(context.value === props.value)
  //
  // Step 3 — 事件處理（Svelte 5 用 onclick 代替 on:click）
  //
  // 📖 參考：
  // - Svelte 5 $derived: https://svelte.dev/docs/svelte/$derived
  // - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/switch/
  // - Ark UI SwitchHiddenInput Svelte 版本：
  //   https://github.com/chakra-ui/ark/blob/main/packages/svelte/src/lib/components/switch/SwitchHiddenInput.svelte
  // ===========================================================================

  // TODO: import context
  // const context = getSwitchContext()

  // TODO: $derived 計算屬性
</script>

<!-- TODO: 渲染 <input> 並加上 ARIA 屬性 -->
<input>
  {@render children?.()}
</input>
