// packages/vue/src/components/popover/PopoverDescription.vue
<script setup lang="ts">
// =============================================================================
// TODO: 實作 PopoverDescription Vue 元件
// =============================================================================
//
// 功能說明：Popover 描述
//
// 💡 提示：
// Step 1 — 從 Context 取得狀態
//   import { usePopoverContext } from './popover-context'
//   const context = usePopoverContext()
//
// Step 2 — 計算 ARIA 屬性（使用 computed）
//
// Step 3 — 事件處理（使用 defineEmits 或直接呼叫 context 方法）
//
// 📖 參考：
// - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/popover/
// - Ark UI PopoverDescription Vue 版本：
//   https://github.com/chakra-ui/ark/blob/main/packages/vue/src/components/popover/PopoverDescription.vue
// =============================================================================

// TODO: 從 Context 讀取狀態
// const context = usePopoverContext()
</script>

<template>
  <!-- TODO: 渲染 <p> 並加上 ARIA 屬性 -->
  <p v-bind="$attrs">
    <slot />
  </p>
</template>

// packages/svelte/src/components/popover/PopoverDescription.svelte
<script lang="ts">
  // ===========================================================================
  // TODO: 實作 PopoverDescription（Svelte 5 版）
  // ===========================================================================
  //
  // 功能說明：Popover 描述
  //
  // 💡 提示：
  // Step 1 — 從 Context 讀取狀態
  //   import { getPopoverContext } from './popover-context.svelte.ts'
  //   const context = getPopoverContext()
  //
  // Step 2 — 計算 ARIA 屬性（使用 $derived）
  //   const isExpanded = $derived(context.value === props.value)
  //
  // Step 3 — 事件處理（Svelte 5 用 onclick 代替 on:click）
  //
  // 📖 參考：
  // - Svelte 5 $derived: https://svelte.dev/docs/svelte/$derived
  // - ARIA Pattern: https://www.w3.org/WAI/ARIA/apg/patterns/popover/
  // - Ark UI PopoverDescription Svelte 版本：
  //   https://github.com/chakra-ui/ark/blob/main/packages/svelte/src/lib/components/popover/PopoverDescription.svelte
  // ===========================================================================

  // TODO: import context
  // const context = getPopoverContext()

  // TODO: $derived 計算屬性
</script>

<!-- TODO: 渲染 <p> 並加上 ARIA 屬性 -->
<p>
  {@render children?.()}
</p>
